"use client";
import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import React, { useState, useEffect } from "react";
import deved from "../public/pic.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const [isClick, setIsClick] = useState(false);

  const toggleNavbar = () => {
    setIsClick(!isClick);
  };

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create portfolio" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section id='home' className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <div className="flex items-center">
              <h1 className="font-burtons text-xl px-2 py-2 rounded-md transition-all duration-500 ease-in-out transform hover:bg-gradient-to-r from-cyan-500 to-teal-500 hover:text-white hover:scale-105 hover:rotate-2 hover:shadow-lg">
                MIDHUN M
              </h1>
            </div>
            <ul className="hidden md:flex items-center space-x-4">
              <li>
                <a href="#home" className="text-xl hover:bg-gradient-to-r from-cyan-500 to-teal-500 px-2 py-2 rounded-md hover:text-white">Home</a>
              </li>
              <li>
                <a href="#about" className="text-xl hover:bg-gradient-to-r from-cyan-500 to-teal-500 px-2 py-2 rounded-md hover:text-white">About</a>
              </li>
              <li>
                <a href="#education" className="text-xl hover:bg-gradient-to-r from-cyan-500 to-teal-500 px-2 py-2 rounded-md hover:text-white">Education</a>
              </li>
              <li>
                <a href="#contact" className="text-xl hover:bg-gradient-to-r from-cyan-500 to-teal-500 px-2 py-2 rounded-md hover:text-white">Contact Me</a>
              </li>
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="resume.pdf" download>Resume</a>
              </li>
            </ul>
            <div className="md:hidden flex items-center">
              <button onClick={toggleNavbar} className="focus:outline-none">
                {isClick ? (
                  <svg className="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                  </svg>
                ) : (
                  <svg className="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16m-7 6h7" />
                  </svg>
                )}
              </button>
            </div>
          </nav>
          {isClick && (
            <div className="md:hidden">
              <ul className="space-y-2">
                <li>
                  <a href="#home" className="block text-xl hover:bg-gradient-to-r from-cyan-500 to-teal-500 px-4 py-2 rounded-md hover:text-white dark:text-white">Home</a>
                </li>
                <li>
                  <a href="#about" className="block text-xl hover:bg-gradient-to-r from-cyan-500 to-teal-500 px-4 py-2 rounded-md hover:text-white dark:text-white">About</a>
                </li>
                <li>
                  <a href="#education" className="block text-xl hover:bg-gradient-to-r from-cyan-500 to-teal-500 px-4 py-2 rounded-md hover:text-white dark:text-white">Education</a>
                </li>
                <li>
                  <a href="#contact" className="block text-xl hover:bg-gradient-to-r from-cyan-500 to-teal-500 px-4 py-2 rounded-md hover:text-white dark:text-white">Contact Me</a>
                </li>
                <li>
                  <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl mx-4 my-2 dark:text-white gap-4 " />
                </li>
                <li className="mt-4">
                  <a className="block bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-4" href="resume.pdf" download>Resume</a>
                </li>
              </ul>
            </div>
          )}
          <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
            <Image src={deved} layout="fill" objectFit="cover" />
          </div>
          <div className="text-center p-10 py-10">
            <h2 className="text-3xl sm:text-4xl md:text-5xl lg:text-6xl xl:text-7xl py-2 text-teal-600 font-medium dark:text-teal-400">
              <span className="inline-block transition-all duration-500 ease-in-out transform hover:bg-white dark:hover:bg-gray-800 hover:text-teal-600 dark:hover:text-teal-400 hover:scale-105 hover:shadow-xl px-2 rounded-md">
                MIDHUN M
              </span>
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Developer and designer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Freelancer providing services for programming and design content
              needs. Join me down below and let's get cracking!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://github.com/Midhun62" target="_blank" rel="noopener noreferrer" className="hover:text-[#181717] dark:hover:text-[#181717] transition-colors">
                <AiFillGithub />
              </a>
              <a href="https://www.linkedin.com/in/midhun-m-851b86225/" target="_blank" rel="noopener noreferrer" className="hover:text-[#0077B5] dark:hover:text-[#0077B5] transition-colors">
                <AiFillLinkedin />
              </a>
              <a href="http://www.youtube.com/@midhunMaxi" target="_blank" rel="noopener noreferrer" className="hover:text-[#FF0000] dark:hover:text-[#FF0000] transition-colors">
                <AiFillYoutube />
              </a>
            </div>
          </div>
        </section>
        <section id="about">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">ABOUT</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Indesign</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Code your dream project
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website? Let's make it a
                reality.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Indesign</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">Consulting</h3>
              <p className="py-2">
                Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Indesign</p>
            </div>
          </div>
        </section>
        <section className="py-10" id="education">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Education</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" src={web1} />
            </div>
            <div className="basis-1/3 flex-1">
              <Image className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" src={web2} />
            </div>
            <div className="basis-1/3 flex-1">
              <Image className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" src={web3} />
            </div>
            <div className="basis-1/3 flex-1">
              <Image className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" src={web4} />
            </div>
            <div className="basis-1/3 flex-1">
              <Image className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" src={web5} />
            </div>
            <div className="basis-1/3 flex-1">
              <Image className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" src={web6} />
            </div>
          </div>
        </section>
        <section className="py-10" id="contact">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Contact Me</h3>
          </div>
        </section>
      </main>
    </div>
  );
}
